name: docs

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup

      - name: Generate docs
        run: yarn docs
      - name: Archive and upload documentation
        uses: actions/upload-pages-artifact@v2
        with:
          name: "docs-main"
          path: ./docs

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    steps:
    - name: Deploy GitHub Pages
      uses: actions/deploy-pages@v2
      with:
        artifact_name: "docs-main"
